logging:
  level:
    com.casper.event: ${LOG_LEVEL:DEBUG}
  file:
    path: ${HOME}/event-consumer.log

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: consumer-events

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8089
