logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:INFO}
  file:
    path: /var/logs/consumer-audit.log

spring:
  data:
    mongodb:
      uri: mongodb://mongo-events-0.mongo-events-service:27017/casper-events,mongo-events-1.mongo-events-service:27017/casper-events

  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_SERVICE_HOST}:${KAFKA_SERVICE_SERVICE_PORT}
    consumer:
      client-id: consumer-audit-client

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8080