apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: store-consumer
  name: store-consumer
  namespace: events
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-consumer
  template:
    metadata:
      labels:
        app: store-consumer
    spec:
      serviceAccount: kafka-account
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: superUserPassword
      containers:
        - image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          imagePullPolicy: Always
          name: store-consumer
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10