apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: store-consumer
  name: store-consumer
  namespace: events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-consumer
  template:
    metadata:
      labels:
        app: store-consumer
    spec:
      serviceAccount: kafka-account
      containers:
        - image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "0.1"
          imagePullPolicy: Always
          name: store-consumer
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10