apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audit-consumer
  name: audit-consumer
  namespace: events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-consumer
  template:
    metadata:
      labels:
        app: audit-consumer
    spec:
      serviceAccount: kafka-account
      containers:
        - image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          imagePullPolicy: Always
          name: audit-consumer
          ports:
            - containerPort: 8080