logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:INFO}
  file:
    path: /var/logs/audit.log

spring:
  data:
    mongodb:
      uri: mongodb://mongo-events-0.mongo-events-service:27017/casper-events,mongo-events-1.mongo-events-service:27017/casper-events?replicaSet=rs0

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8080
  forward-headers-strategy: framework

