logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    path: ${HOME}/event-store-audit-consumer.log

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: consumer-audit-client-01
      group-id: consumer-audit

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    tags-sorter: alpha

server:
  port: 8081