logging:
  level:
    com.casper.event: ${LOG_LEVEL:DEBUG}
  file:
    path: ${HOME}/event-store-audit-consumer.log

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: consumer-audit
      group-id: consumer-audit

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8088