apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: events
  labels:
    name: producer-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  clusterIP: None
  selector:
    app: producer-consumer