services:
  emitters:
    - ${CASPER_EVENTS_MAIN:http://135.181.14.226:9999}
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    name: ${HOME}/cspr-producer.log
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: stormeye-kafka-local

  data:
    mongodb:
      uri: mongodb://localhost:27017/casper-producer