apiVersion: v1
kind: Service
metadata:
  name: audit-api-service
  namespace: events
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: audit-api
  type: NodePort