apiVersion: v1
kind: Service
metadata:
  name: store-api-service
  namespace: events
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: store-api
  type: NodePort